name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm install -D release-it
      - run: npm install -D @release-it/bumper
      - run: npm install -D @release-it/conventional-changelog
      
      - name: Release-it
        uses: TheRealWaldo/release-it@v0.2.1
        with:
          json-opts: '{"prepatch": true}'