name: CI2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/setup-node@v2
      - run: npm install

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: release-it
        uses: TheRealWaldo/release-it@v0.2.1