name: CI2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm install -D release-it
      - run: npm install -D @release-it/bumper

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: release-it
        uses: TheRealWaldo/release-it@v0.2.1