name: increase_version_major_number
on:
  workflow_dispatch

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - name: Validate branch
        if: {{ github.ref != 'ref/head/development' }}
        run: echo This should be run only on development branch
        run: exit 1
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: development

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: npm install -D release-it
      - run: npm install -D @release-it/bumper
      
      - name: Release-it
        uses: TheRealWaldo/release-it@v0.2.1
        with:
          json-opts: '{"increment": "major"}'